# Generated by Django 3.2.2 on 2021-06-07 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_code', models.CharField(max_length=12, null=True, primary_key=True, serialize=False)),
                ('exam_name', models.CharField(blank=True, max_length=12, null=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('exam_type', models.CharField(blank=True, max_length=12, null=True)),
                ('exam_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(blank=True, max_length=12, null=True)),
                ('capacity', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeatPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cul_no', models.CharField(blank=True, max_length=12, null=True)),
                ('row_no', models.CharField(blank=True, max_length=12, null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.room')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(blank=True, max_length=12, null=True)),
                ('stu_level', models.CharField(blank=True, max_length=10, null=True)),
                ('stu_dept', models.CharField(blank=True, max_length=12, null=True)),
                ('stu_mail', models.CharField(blank=True, max_length=50, null=True)),
                ('exam', models.ManyToManyField(blank=True, null=True, to='myapp.Exam')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.room')),
                ('seat', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.seatplan')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_name', models.CharField(blank=True, max_length=12, null=True)),
                ('fac_mail', models.CharField(blank=True, max_length=50, null=True)),
                ('fac_phone_no', models.CharField(blank=True, max_length=12, null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.room')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
