# Generated by Django 3.2.2 on 2021-06-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_exam_exam_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='room',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.Room'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_time',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
