# Generated by Django 3.2.2 on 2021-06-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210608_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='seatplan',
            name='seat_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
