# Generated by Django 3.2.2 on 2021-06-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210608_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
