# Generated by Django 3.2.2 on 2021-06-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_student_stu_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_roll',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
