# Generated by Django 3.2.2 on 2021-06-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210610_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(blank=True, max_length=12, null=True),
        ),
    ]
