# Generated by Django 3.2.2 on 2021-06-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_room_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='room',
        ),
    ]
