# Generated by Django 3.2.2 on 2021-06-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stu_term',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
